### ISSUE TITLE
crashes when uploading dataset on mac

### ISSUE THREAD

**Issue by dpastoor** [isop-phmx/GGplot-Shiny#1]
```
Error in `[.data.frame`(plotdata, , input$y_input) : 
  undefined columns selected
Warning: Unhandled error in observer: undefined columns selected
observe({
    inputx <- input$x_input
    data2 <- myData()
    val1 <- min(min(data2[, input$x_input]), 0)
    val2 <- max(data2[, input$x_input])
    val <- c(val1, val2)
    updateSliderInput(session, "receivex", value = val, min = val1, 
        max = val2, step = (val2 - val1)/10)
})
Warning: Unhandled error in observer: undefined columns selected
observe({
    inputx <- input$y_input
    data2 <- myData()
    val1 <- min(min(data2[, input$y_input]), 0)
    val2 <- max(data2[, input$y_input])
    val <- c(val1, val2)
    updateSliderInput(session, "receivey", value = val, min = val1, 
        max = val2, step = (val2 - val1)/10)
})
```

**Comment by smouksassi** [comment]
This should not happen but please test on Mac and let me know. The only known issue is that your filter variables should be set to none before you upload another data.

**Comment by dpastoor** [comment]
just as you said - it crashes when i upload a second dataset 

the 'workaround' should be to modify the read function to automatically reset the column inputs to 'None' when detecting a change to the reactive datasource (aka when a new file is uploaded)

**Comment by smouksassi** [comment]
```
                                                                                  Does is work when no filter is applied ?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Devin PastoorSent: Friday, March 20, 2015 11:59To: isop-phmx/GGplot-ShinyReply To: isop-phmx/GGplot-ShinyCc: Samer MouksassiSubject: Re: [GGplot-Shiny] crashes when uploading dataset on mac (#1)just as you said - it crashes when i upload a second dataset 
```

the 'workaround' should be to modify the read function to automatically reset the column inputs to 'None' when detecting a change to the reactive datasource (aka when a new file is uploaded)

—Reply to this email directly or view it on GitHub.

**Comment by dpastoor** [comment]
I didn't even try filtering - I just uploaded the hba1c dataset, selected two columns, then tried uploading the sample_data.csv and it immediately crashed.

**Comment by dpastoor** [comment]
fixed in e483d680c867b65d38e7418b1a7129c08dc95978 for at least basic x and y inputs causing crashing. Have not looked into what is going on with filter, it would likely be best to reset all inputs on upload in a function that can be easily called. 

That would also 'future' proof against the situation where someone wants to pass in multiple datasets with teh same structure and settings so they could 'uncheck' reset all inputs.

**Comment by smouksassi** [comment]
ok I did a quick around that can be found:
https://pharmacometrics.shinyapps.io/ggplotmydata/ggplotwithyourdata.Rmd 

(if you test and it seems working I will commit it) note that it seems to be abug that the values of the filter don't go to null when filter variable = none but for now I want to know if the web based app work 
Thank you again !

**Comment by dpastoor** [comment]
nope filter still isn't working on the webapp 
![image](https://cloud.githubusercontent.com/assets/3196313/6759344/c2fab648-cf15-11e4-98a3-77f6e832b0be.png) (should only be ID 23 showing)

**Comment by smouksassi** [comment]
The expected behavior is that the values that are shown are in the data. so above you need to delete all th evalues except 23 then it will shows ID 23 only. I agree it is not ideal but having a value highlighted or seleceted by mouse trigger 
![id23](https://cloud.githubusercontent.com/assets/5131281/6759571/63f60ce0-cf17-11e4-8fe7-f440b8b48d15.png)
nothing what really trigger things is the list of values currently selected.

**Comment by dpastoor** [comment]
yes but i'm clicking on 23 but its not selecting...

**Comment by smouksassi** [comment]
cannot reproduce on my end when you clinck the mouse on a value you can hit delete or back space to delete the highlited value

**Comment by dpastoor** [comment]
ah i see, you can't delete with a mouse click (it just selects it?) - this is very weird an non-intuitive. Hmm there has to be a better widget or something

**Comment by smouksassi** [comment]
yep for now this is how it is implemented and I agree not ideal. More suitable when your filter variable has limited number of values i.e a treatment arm a study challenging when you have ID with 100 or 1000's values !

**Comment by dpastoor** [comment]
we should look and see if there is a checkbox style widget like excel style filtering - that would probably be best

**Comment by smouksassi** [comment]
maybe a selectinput without selectize=T is what you are asking for ?
http://shiny.rstudio.com/gallery/selectize-vs-select.html

**Comment by dpastoor** [comment]
nah checkboxGroupInput looks like the better option

```
 checkboxGroupInput("checkGroup", label = h3("Checkbox group"), 
    choices = list("Choice 1" = 1, "Choice 2" = 2, "Choice 3" = 3),
    selected = 1)
```

http://shiny.rstudio.com/gallery/widget-gallery.html

**Comment by smouksassi** [comment]
test the web app again now filter variable one is selection based like you asked and the second filter variable is the old style now you can just highlight the id even control a  all to select all

**Comment by dpastoor** [comment]
i think some of the issue is the UX on the widgets needs a lot of work - for example just by messing around you can select multiple with shift

![image](https://cloud.githubusercontent.com/assets/3196313/6760582/7d79c9aa-cf20-11e4-966c-bfbcea4e79bc.png)

The other thing I somewhat accidentally ran into is this is a good place to put in a length(unique(x)) statement before even letting a user ask to filter a row - I accidentally clicked conc and it caused the app to choke and eventually crash (locally thankfully).

**Comment by smouksassi** [comment]
```
                                                                                  Added a limit of 250 unique values for the variable to appear in filter list.‎The user can change the value if he wants.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Devin PastoorSent: Friday, March 20, 2015 18:54To: isop-phmx/GGplot-ShinyReply To: isop-phmx/GGplot-ShinyCc: Samer MouksassiSubject: Re: [GGplot-Shiny] crashes when uploading dataset on mac (#1)i think some of the issue is the UX on the widgets needs a lot of work - for example just by messing around you can select multiple with shift
```

The other thing I somewhat accidentally ran into is this is a good place to put in a length(unique(x)) statement before even letting a user ask to filter a row - I accidentally clicked conc and it caused the app to choke and eventually crash (locally thankfully). 

—Reply to this email directly or view it on GitHub.

**Comment by dpastoor** [comment]
good idea, lets branch this off into another issue

**Comment by dpastoor** [comment]
moved to issue #4

**Comment by smouksassi** [comment]
while the UX can still be improved everything is currently working future improvement will include some isolate() and some validate() statements
