### ISSUE TITLE
chrome for mac with shinapps.io version also hangs

### ISSUE THREAD

**Issue by dpastoor** [isop-phmx/GGplot-Shiny#3]
![image](https://cloud.githubusercontent.com/assets/3196313/6471307/bb4fbb84-c1b7-11e4-9fd0-cc85d8d67d4c.png)

**Comment by dpastoor** [comment]
hmm also not working for me on windows. @smouksassi can you check to see if everything is working for the shinapps.io implementation for you?

**Comment by smouksassi** [comment]
Please test the latest version this has been fixed.
