### ISSUE TITLE
set limits on number of filter values before will not allow (for performance reasons)

### ISSUE THREAD

**Issue by dpastoor** [isop-phmx/GGplot-Shiny#4]
Initially, the best option would be to do a quick check to make sure less than, I would actually say more like 50-100? I guess we can check to see where the performance degrades significantly.

Eventually, we could probably base the selection criteria based on certain checkpoints - eg if <50 or something then have the select unique values, but if more then have like a slider (0-x) where person can select some range to be within

**Comment by smouksassi** [comment]
added a slider default n unique to 250 and can be easily changed and increased or decreased. Once I test the performance I might set a higher limit.

**Comment by smouksassi** [comment]
I tested the webapp version with conc set as filter and performance were acceptable.
