### ISSUE TITLE
I cannot see your code

### ISSUE THREAD

**Issue by gsaray101** [isop-phmx/GGplot-Shiny#5]
can you share your code?

**Comment by smouksassi** [comment]
I will checkCode should be on github                                                                                                                                                                                                                                                                                                                                        Swipe typed from Blackberry.                                                                                                                                                                                                                From: gsaray101Sent: Wednesday, January 20, 2016 11:34To: isop-phmx/GGplot-ShinyReply To: isop-phmx/GGplot-ShinySubject: [GGplot-Shiny] I cannot see your code (#5)can you share your code?

—Reply to this email directly or view it on GitHub.

**Comment by smouksassi** [comment]
code at https://github.com/isop-phmx/GGplot-Shiny/blob/master/GGPLOTSHINY.Rmd

**Comment by gsaray101** [comment]
Hi Samee,

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone-------- Original message --------From: Samer Mouksassi notifications@github.com Date: 1/20/2016  4:42 PM  (GMT-05:00) To: isop-phmx/GGplot-Shiny GGplot-Shiny@noreply.github.com Cc: gsaray101 gsaray101@yahoo.com Subject: Re: [GGplot-Shiny] I cannot see your code (#5) 
code at https://github.com/isop-phmx/GGplot-Shiny/blob/master/GGPLOTSHINY.Rmd

**Comment by gsaray101** [comment]
Hi Samer,
What if x-axis was timedate, and when the pulled in data from the csv needs to be concerted to Posix, any ideas how we would tackle this?
Thanks

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone-------- Original message --------From: Samer Mouksassi notifications@github.com Date: 1/20/2016  4:42 PM  (GMT-05:00) To: isop-phmx/GGplot-Shiny GGplot-Shiny@noreply.github.com Cc: gsaray101 gsaray101@yahoo.com Subject: Re: [GGplot-Shiny] I cannot see your code (#5) 
code at https://github.com/isop-phmx/GGplot-Shiny/blob/master/GGPLOTSHINY.Rmd

**Comment by smouksassi** [comment]
```
                                                                                  Currently I have no special handling for date variablesHappy to review a pull requestFor now only categorical or continuous are supported and sliders appear only for continuousDo you have a test data ?                                                                                                                                                                                                                 From: gsaray101Sent: Wednesday, January 20, 2016 17:01To: isop-phmx/GGplot-ShinyReply To: isop-phmx/GGplot-ShinyCc: Samer MouksassiSubject: Re: [GGplot-Shiny] I cannot see your code (#5)Hi Samer,
```

What if x-axis was timedate, and when the pulled in data from the csv needs to be concerted to Posix, any ideas how we would tackle this?
Thanks

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone-------- Original message --------From: Samer Mouksassi notifications@github.com Date: 1/20/2016  4:42 PM  (GMT-05:00) To: isop-phmx/GGplot-Shiny GGplot-Shiny@noreply.github.com Cc: gsaray101 gsaray101@yahoo.com Subject: Re: [GGplot-Shiny] I cannot see your code (#5) 
code at https://github.com/isop-phmx/GGplot-Shiny/blob/master/GGPLOTSHINY.Rmd 

—
Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

**Comment by gsaray101** [comment]
Test data would be like
Date server  cpu14JUN15:12:00:00,web101,100

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone-------- Original message --------From: Samer Mouksassi notifications@github.com Date: 1/20/2016  8:04 PM  (GMT-05:00) To: isop-phmx/GGplot-Shiny GGplot-Shiny@noreply.github.com Cc: gsaray101 gsaray101@yahoo.com Subject: Re: [GGplot-Shiny] I cannot see your code (#5) 
                                                                                      Currently I have no special handling for date variablesHappy to review a pull requestFor now only categorical or continuous are supported and sliders appear only for continuousDo you have a test data ?                                                                                                                                                                                                                 From: gsaray101Sent: Wednesday, January 20, 2016 17:01To: isop-phmx/GGplot-ShinyReply To: isop-phmx/GGplot-ShinyCc: Samer MouksassiSubject: Re: [GGplot-Shiny] I cannot see your code (#5)Hi Samer,

What if x-axis was timedate, and when the pulled in data from the csv needs to be concerted to Posix, any ideas how we would tackle this?

Thanks

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone-------- Original message --------From: Samer Mouksassi notifications@github.com Date: 1/20/2016  4:42 PM  (GMT-05:00) To: isop-phmx/GGplot-Shiny GGplot-Shiny@noreply.github.com Cc: gsaray101 gsaray101@yahoo.com Subject: Re: [GGplot-Shiny] I cannot see your code (#5) 

code at https://github.com/isop-phmx/GGplot-Shiny/blob/master/GGPLOTSHINY.Rmd 

—

Reply to this email directly or view it on GitHub.

—Reply to this email directly or view it on GitHub.

—
Reply to this email directly or view it on GitHub.
