### ISSUE TITLE
datetime formating issues on x-axis

### ISSUE THREAD

**Issue by gsaray101** [isop-phmx/GGplot-Shiny#6]
If there was way to convert the datetime into posix or date format on x-axis, this would be perfect.

**Comment by gsaray101** [comment]
before loading the data, I even converted the data to POSIXct like 2015-02-14 09:00:00, still I dont see the x-axis as date. I cannot even read it, it is assuming it as factor. There is no scale.

**Comment by gsaray101** [comment]
In graph options tab, I see x-axis label, would it be easier to put a data format so that depending on the datetime format in csv, we can overwrite it by suppliying the function. For example, if the x-asix value in date format we should be able to pick it as.Date and the format of the date field (as.Date, %m/%d/%Y) or as.Datetime, %m%d%YY 09:00:00. Any thoughts?

**Comment by smouksassi** [comment]
I can test for dateinput and disallow it otherwise I don't have bandwidth would be interested to provide a PR ?  as for the x axis lable for now it only allow for "text" input please provide a reproducible example to understand what you are trying to do

**Comment by gsaray101** [comment]
for xaxis, there should be check box to pick whether the xaxis is in datetime or numeric field. If the datetime is picked, there should be a textbox to format the xaxis values. The values in the text box need to be applied to the values in xaxis to re-format so that date values can be seen in the ggplot. For example, if xaxis values like this 2015-05-01, user should put this in the text box %YY-%m-%d or if the xaxis values like this 2015-05-01 01:00:00 the values %YY-%m-%d %H:%M:%S. There should be button to apply this to the values of xaxis. 

DateTime    CPU_Usage
02NOV15:00:00:52    20
02NOV15:00:15:52    20
02NOV15:00:30:52    8
02NOV15:00:45:52    8
02NOV15:01:00:52    12
02NOV15:01:15:52    16
02NOV15:01:30:52    49
02NOV15:01:45:52    30
02NOV15:02:00:52    28
02NOV15:02:15:52    27
02NOV15:02:30:52    21
02NOV15:02:45:52    18

**Comment by gsaray101** [comment]
Does this make sense? Your app is perfect, if the timestamp formating option was that it could be more perfect.

**Comment by smouksassi** [comment]
Hi @gsaray101  will keep the issue open for now and put this on the to do list for my next time around ! thanks for your kind comments we can always improve things. Again if you would like to start pulling out the changes please issue a PR bests.

**Comment by smouksassi** [comment]
@gsaray101 can you provide a minimal repoducible example where you generate the plot you would like to have with the app using r code ? then I can look how to make these options into the app and put it on the road map.

**Comment by smouksassi** [comment]
Hi @gsaray101  I did not hear back from you closing for now  please note that in the new version of the app  you can do a plot like below. Currently there is no capabilities to import and format time /datetime variable. As mentioned above if you have rproducible code we can make it into the app. (start from a csv, r code to format etc. then we plot)
![timeaxis](https://user-images.githubusercontent.com/5131281/27193542-2fbf4ac8-51cd-11e7-9479-d44f32c16f83.png)
