### ISSUE TITLE
TableTools is no longer available

### ISSUE THREAD

**Issue by bgnj2017** [isop-phmx/GGplot-Shiny#7]
Extensions TableTools have been retired and the version that is archived does not have the following extension: '//cdn.datatables.net/tabletools/2.2.4/js/ZeroClipboard.min.js'

Do you have an updated scripts?

**Comment by smouksassi** [comment]
new version of the app which is in active development is located here.
https://github.com/smouksassi/ggplotwithyourdata
let me know if this works for you.
